// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDhum7yT1Lx5_KQueVdHoZ7wbp5IqZBA',
    appId: '1:248581530281:web:498926c9dbef97c90e3fb8',
    messagingSenderId: '248581530281',
    projectId: 'journal-app-acd37',
    authDomain: 'journal-app-acd37.firebaseapp.com',
    storageBucket: 'journal-app-acd37.appspot.com',
    measurementId: 'G-BTCN6MQ5TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw80Hyx8FwR1kop5ZncraYZY2QyQBDg7c',
    appId: '1:248581530281:android:756e795631eddb790e3fb8',
    messagingSenderId: '248581530281',
    projectId: 'journal-app-acd37',
    storageBucket: 'journal-app-acd37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgODvTbWnbGpP5s5Cty239w-oR7oKbxzo',
    appId: '1:248581530281:ios:82f1f5130af87c110e3fb8',
    messagingSenderId: '248581530281',
    projectId: 'journal-app-acd37',
    storageBucket: 'journal-app-acd37.appspot.com',
    iosBundleId: 'com.samri.journalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgODvTbWnbGpP5s5Cty239w-oR7oKbxzo',
    appId: '1:248581530281:ios:82f1f5130af87c110e3fb8',
    messagingSenderId: '248581530281',
    projectId: 'journal-app-acd37',
    storageBucket: 'journal-app-acd37.appspot.com',
    iosBundleId: 'com.samri.journalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNDhum7yT1Lx5_KQueVdHoZ7wbp5IqZBA',
    appId: '1:248581530281:web:1e4936ed5751dcd70e3fb8',
    messagingSenderId: '248581530281',
    projectId: 'journal-app-acd37',
    authDomain: 'journal-app-acd37.firebaseapp.com',
    storageBucket: 'journal-app-acd37.appspot.com',
    measurementId: 'G-96L467Y2HY',
  );
}
